version: '3.8'

services:
  mcp-client:
    image: mcp-client:0.1
    ports:
      - "8501:8501"
    volumes:
      - mcp_client:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    entrypoint: ["./entrypoint.sh"]
  n8n:
    image: n8nio/n8n:1.90.0
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_PORT=5678
      - NODE_ENV=production
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local_files:/files

volumes:
  mcp_client:
  n8n_data:

networks:
  default:
    name: mcp-network
    driver: bridge