version: '3.8'

services:
  mcp-client:
    image: mcp-client:0.1
    ports:
      - "8501:8501"
    volumes:
      - mcp_client:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    entrypoint: ["./entrypoint.sh"]

volumes:
  mcp_client:

networks:
  default:
    name: mcp-network
    driver: bridge