[project]
name = "meetmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]==1.6.0",
    "nest-asyncio==1.6.0",
    "pillow==11.2.1",
    "streamlit==1.44.1",
]
